# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello <- function() {
    .Call(`_simplin_rcpp_hello`)
}

simp_lin_cpp <- function(x, y, n) {
    .Call(`_simplin_simp_lin_cpp`, x, y, n)
}

